### ISSUE TITLE
iOS 工程下的 ijksdl 如何继承到工程中去呢

### ISSUE THREAD

**Issue by maker997** [netease-im/Wawaji#3]
把 ijksdl 文件夹拖入到工程就会报错

**Comment by chrisray108** [comment]
需要在你的工程中配置 header search path, 为 ijksdl 的上级目录，可以参考 Demo 的配置

**Comment by maker997** [comment]
嗯嗯,已经解决

**Comment by Robinguo2012** [comment]
@maker997  请问怎么解决的，我看现在Demo中也没有配置啊。
